### ISSUE TITLE
EF Core logo, pleeease!

### ISSUE THREAD

**Issue by ErikEJ** [campusMVP/dotnetCoreLogoPack#1]
Great initiative - Please add a logo for EF Core also!
(Same color as the .NET Core logo)

**Comment by jmalarcon** [comment]
Will do!

**Comment by jmalarcon** [comment]
Hey Erik:

We've just added logos for EF Core too :-)

HTH

**Comment by ErikEJ** [comment]
Great! thanks

**Comment by piglesias** [comment]
Hi @ErikEJ,

Please, let us know if you use it! :-)

Enjoy!

**Comment by ErikEJ** [comment]
In use here: https://github.com/ErikEJ/EntityFramework.SqlServerCompact

**Comment by jmalarcon** [comment]
Grrreat! :-)

Thanks for telling me.


•••••••••••••••••••••••••••••
*JOSÉ M. ALARCÓN*
jmalarcon@jasoft.org
t: @jm_alarcon <http://twitter.com/#!/@jm_alarcon>
b: jmalarcon.es
b: jasoft.org
•••••••••••••••••••••••••••••
