### ISSUE TITLE
Try different version

### ISSUE THREAD

**Issue by kjbetz** [campusMVP/dotnetCoreLogoPack#2]
I really like what you've done here. I really like the take on Core. I wonder if this idea would emphasize ".NET Core" and also make the logos not as long in width.

Could you try a set of logos like this:

.NET Core (the same way you have it.)

ASP
.NET Core

ASP
.NET Core
MVC

Also, definitely one for EntityFramework!

**Comment by jmalarcon** [comment]
We have variations for all of that.  In fact we have the variation with "Core" big below ".NET" put into t-shirts.

We'll try to publish them soon.

Thanks

**Comment by jmalarcon** [comment]
Hi Kristopher:

Sorry for the delay doing this (too many things onour plate these days), but we've added more "squared" logos to the repo as you requested. We've already used some of them for T-Shirts and other swag :-)

Cheers!
